# Generated by Django 6.0.6 on 2026-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency_type",
            field=models.CharField(
                choices=[("daily", "Каждый день"), ("every_n_days", "Каждые N дней")],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency_value",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
